<?php

use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

class RefillAllAuthorsTable extends Migration {

	/**
	 * Run the migrations.
	 *
	 * @return void
	 */
	public function up()
	{
		DB::table('authors')->insert(    		array(

array("name" =>"ABREU JÚNIOR, Júlio de", "approved" => 1),
array("name" =>"ABREU, joão Clodomiro de", "approved" => 1),
array("name" =>"ABREU, José Coelho da Gama e", "approved" => 1),
array("name" =>"ADORNO, Álvaro Rodrigues ", "approved" => 1),
array("name" =>"ADORNO, José", "approved" => 1),
array("name" =>"AFLALO FILHO, Roberto", "approved" => 1),
array("name" =>"AFLALO, Roberto", "approved" => 1),
array("name" =>"AGUIAR, Francisco Marcelino de Souza", "approved" => 1),
array("name" =>"AGUIAR, Walmir Santos", "approved" => 1),
array("name" =>"Albuquerque & Longo", "approved" => 1),
array("name" =>"ALBUQUERQUE, Alexandre", "approved" => 1),
array("name" =>"ALMEIDA, Bernardino Sena Reis e", "approved" => 1),
array("name" =>"ALMEIDA, Carlos Luís de", "approved" => 1),
array("name" =>"ALPOIM, José Fernandes Pinto", "approved" => 1),
array("name" =>"ÁLVARES, Padre João", "approved" => 1),
array("name" =>"ALVES, Hermillo Cândido da Costa", "approved" => 1),
array("name" =>"AMARAL, Ângelo Thomaz do", "approved" => 1),
array("name" =>"AMARAL, Walmyr Lima", "approved" => 1),
array("name" =>"ANCHIETA, José de", "approved" => 1),
array("name" =>"ANDRADA, Martim Francisco Ribeiro de", "approved" => 1),
array("name" =>"ANHAIA MELLO, Luiz Ignácio Romeiro de", "approved" => 1),
array("name" =>"ANJOS, Frei Rodrigo dos", "approved" => 1),
array("name" =>"ANNES, Álvaro", "approved" => 1),
array("name" =>"ANTIQUEIRA, Domingos de Castro", "approved" => 1),
array("name" =>"Antônio Menéres Planejamento e Arquitetura", "approved" => 1),
array("name" =>"ARAÚJO, Cláudio Luiz", "approved" => 1),
array("name" =>"ARTIGAS, João Batista Vilanova", "approved" => 1),
array("name" =>"ARZÃO, Cornélio", "approved" => 1),
array("name" =>"ASCENÇÃO, Frei Mateus da", "approved" => 1),
array("name" =>"AZAMBUJA, Ary Fontoura de", "approved" => 1),
array("name" =>"Azevedo & Travassos S/A", "approved" => 1),
array("name" =>"AZEVEDO, Antonio Mariano de", "approved" => 1),
array("name" =>"AZEVEDO, Orlando", "approved" => 1),
array("name" =>"AZEVEDO, Thomás Antonio de", "approved" => 1),
array("name" =>"BADRA JÚNIOR, Miguel", "approved" => 1),
array("name" =>"BAHIANA, Elisário Antônio da Cunha", "approved" => 1),
array("name" =>"BAHIANA, Elisiário Antonio da Cunha ", "approved" => 1),
array("name" =>"Banco Nacional da Habitação (BNH)", "approved" => 1),
array("name" =>"BARBOSA, José Caetano Horta", "approved" => 1),
array("name" =>"BARDI, Achillina Bo", "approved" => 1),
array("name" =>"BARROS, Ary de Queiroz", "approved" => 1),
array("name" =>"BARROS, Luiz Antonio Recamán", "approved" => 1),
array("name" =>"BARTALINI, Vladimir", "approved" => 1),
array("name" =>"BASTIDE, H.", "approved" => 1),
array("name" =>"BASTOS, Pedro Paulo Bernardes", "approved" => 1),
array("name" =>"BECK, Francisco", "approved" => 1),
array("name" =>"BECKER, Alfredo Ernesto", "approved" => 1),
array("name" =>"BELLUCCI, José Augusto e José Carlos ", "approved" => 1),
array("name" =>"BENNATON, Newton", "approved" => 1),
array("name" =>"BENTO, Joaquim Ferreira", "approved" => 1),
array("name" =>"BERGAMIN, Antônio Sérgio", "approved" => 1),
array("name" =>"BERNARDES, Sérgio Wladimir", "approved" => 1),
array("name" =>"BERRONE, João Emanuel", "approved" => 1),
array("name" =>"BERTOLDI, Bianchi", "approved" => 1),
array("name" =>"BLOEM, João", "approved" => 1),
array("name" =>"BÖHM, Gottfried", "approved" => 1),
array("name" =>"BOLONHA, Francisco de Paula Lemos", "approved" => 1),
array("name" =>"BONFIM JÚNIOR, Léo", "approved" => 1),
array("name" =>"BONINI, Cristóforo", "approved" => 1),
array("name" =>"BONINI, Cristóvão", "approved" => 1),
array("name" =>"BOTELHO, Álvaro Carlos de Arruda", "approved" => 1),
array("name" =>"BOTTI, Carlos Amélio", "approved" => 1),
array("name" =>"BRAGA, Diogo", "approved" => 1),
array("name" =>"BRANCO, Pedro Pereira Rio", "approved" => 1),
array("name" =>"BRATKE, Oswaldo Arthur", "approved" => 1),
array("name" =>"BRAZ, Padre Afonso", "approved" => 1),
array("name" =>"BRAZIL, Álvaro Vital", "approved" => 1),
array("name" =>"BRERETON, Robert Pearson", "approved" => 1),
array("name" =>"BRESSER, Carlos Abrão", "approved" => 1),
array("name" =>"BRITO, Fernando Saturnino de", "approved" => 1),
array("name" =>"BRITO, Francisco Saturnino Rodrigues de", "approved" => 1),
array("name" =>"BRUNA, Paulo Júlio Valentino", "approved" => 1),
array("name" =>"BRUNLESS, James", "approved" => 1),
array("name" =>"BUARRAJ, Munir", "approved" => 1),
array("name" =>"BUSSAB, Sami", "approved" => 1),
array("name" =>"CAIUBY, Nestor Dale", "approved" => 1),
array("name" =>"CAIUBY, Olavo Franco", "approved" => 1),
array("name" =>"CALHEIROS, Antônio Pereira Sousa", "approved" => 1),
array("name" =>"CAMARGO, Mauro Álvaro de Souza", "approved" => 1),
array("name" =>"CAMERON, John", "approved" => 1),
array("name" =>"Campbell e Projetos Arquitetos Associados", "approved" => 1),
array("name" =>"CAMPELLO, Glauco", "approved" => 1),
array("name" =>"CAMPOS FILHO, Cândido Malta", "approved" => 1),
array("name" =>"CAMPOS, Antônio José de ", "approved" => 1),
array("name" =>"CANDIA, Salvador", "approved" => 1),
array("name" =>"CARDIM FILHO, Carlos Alberto Gomes", "approved" => 1),
array("name" =>"CARDOSO, Lourenço", "approved" => 1),
array("name" =>"CARMELO, Frei Jesuíno do Monte", "approved" => 1),
array("name" =>"CARNEIRO, Antonio Dias", "approved" => 1),
array("name" =>"CARODOZO, Roberto Coelho", "approved" => 1),
array("name" =>"CARVALHO, Adelmar da Costa", "approved" => 1),
array("name" =>"CARVALHO, Flávio Resende de ", "approved" => 1),
array("name" =>"CARVALHO, Francisco Antônio Pereira de", "approved" => 1),
array("name" =>"CARVALHO, Osmar", "approved" => 1),
array("name" =>"Casa de Projetos Arquitetos Associados", "approved" => 1),
array("name" =>"CASCALDI, Carlos", "approved" => 1),
array("name" =>"CASÉ, Paulo Hamilton", "approved" => 1),
array("name" =>"CASTRO, André Álvares de", "approved" => 1),
array("name" =>"CAVALCANTI, Hélio Uchoa", "approved" => 1),
array("name" =>"CELLIGOI, Jorge", "approved" => 1),
array("name" =>"CERQUEIRA, Francisco de Lima", "approved" => 1),
array("name" =>"CÉSAR, Roberto Cerqueira", "approved" => 1),
array("name" =>"CHAGAS, José Plínio", "approved" => 1),
array("name" =>"CIAMPAGLIA, Galiano", "approved" => 1),
array("name" =>"CIANCIARULLO, Cláudio", "approved" => 1),
array("name" =>"COIMBRA, Frei Francisco de", "approved" => 1),
array("name" =>"COLFOSCO, João Antônio Luiz Carrara", "approved" => 1),
array("name" =>"COMAS, Carlos Eduardo Dias", "approved" => 1),
array("name" =>"Companhia Auxiliar de Serviços de Administração – CASA", "approved" => 1),
array("name" =>"Companhia Metropolitana de Habitação Ltda.", "approved" => 1),
array("name" =>"Companhia Metropolitana de São Paulo", "approved" => 1),
array("name" =>"CONDE, Luiz Paulo Fernandez", "approved" => 1),
array("name" =>"Construtora Adolpho Lindenberg", "approved" => 1),
array("name" =>"Construtora Albuquerque Takaoka", "approved" => 1),
array("name" =>"Construtora Metropolitana de Habitação de SP", "approved" => 1),
array("name" =>"Construtora Warchavchick-Newmann Ltda.", "approved" => 1),
array("name" =>"CORONA, Eduardo ", "approved" => 1),
array("name" =>"CÔRREA, Manoel Kosciuszko Pereira da Silva", "approved" => 1),
array("name" =>"COSTA, João José da Silva", "approved" => 1),
array("name" =>"COSTA, Lúcio Marçal Ferreira Ribeiro de Lima e", "approved" => 1),
array("name" =>"COSTA, Rufino José Felizardo e", "approved" => 1),
array("name" =>"CRISTOFANI, Telesforo Giorgio", "approved" => 1),
array("name" =>"CROCE, Plínio", "approved" => 1),
array("name" =>"CUNHA, Adhemar Marinho", "approved" => 1),
array("name" =>"D' ORDON, Robert Milligan", "approved" => 1),
array("name" =>"D'ANDREATTA, Ana Regina", "approved" => 1),
array("name" =>"DANIEL, Alberto", "approved" => 1),
array("name" =>"D'ANNENCY, Frei Germano", "approved" => 1),
array("name" =>"DE LA VEGA, Joaquim de Soto Garcia", "approved" => 1),
array("name" =>"DENTE, Edgar Gonçalves", "approved" => 1),
array("name" =>"DIAS, Francisco", "approved" => 1),
array("name" =>"DIAS, Marcos de Souza", "approved" => 1),
array("name" =>"DINIZ, Raimundo Nonato da Rocha", "approved" => 1),
array("name" =>"DRIVER, Charles Henry", "approved" => 1),
array("name" =>"DUARTE, Hélio de Queiroz", "approved" => 1),
array("name" =>"DUBUGRAS, Victor", "approved" => 1),
array("name" =>"DUTRA, Miguel Archanjo Benício da Assumpção", "approved" => 1),
array("name" =>"EKMAN, Carlos", "approved" => 1),
array("name" =>"Empresa de Trilhos Urbanos ", "approved" => 1),
array("name" =>"Empresa Municipal de Urbanização ", "approved" => 1),
array("name" =>"Escritório de Architetura e Construção Olavo Franco Caiuby", "approved" => 1),
array("name" =>"Escritório Ramos de Azevedo", "approved" => 1),
array("name" =>"Escritório Técnico H. C. Pujol Jr., Fred Reiman, Tito de Carvalho", "approved" => 1),
array("name" =>"Escritório Técnico Ramos de Azevedo, Severo & Villares S. A.", "approved" => 1),
array("name" =>"Escritório Técnico Samuel e Christiano das Neves", "approved" => 1),
array("name" =>"Escritório Técnico Siciliano e Silva", "approved" => 1),
array("name" =>"ESTEVES, José Pais", "approved" => 1),
array("name" =>"FARIA, José Custódio de Sá e", "approved" => 1),
array("name" =>"FARIA, Teodório Rodrigues de", "approved" => 1),
array("name" =>"FAYET, Carlos Maximiliano", "approved" => 1),
array("name" =>"FELDMAN, Miguel", "approved" => 1),
array("name" =>"FERNANDES, Domingos", "approved" => 1),
array("name" =>"FERNANDES, Lygia", "approved" => 1),
array("name" =>"FERREIRA, Cristóvão José", "approved" => 1),
array("name" =>"FERREIRA, João da Costa", "approved" => 1),
array("name" =>"FERREIRA, José Mamede Alves", "approved" => 1),
array("name" =>"FIDIÉ, Cosme Daminhão da Cunha", "approved" => 1),
array("name" =>"FILHO, Silveira", "approved" => 1),
array("name" =>"FILICAIA, Baccio de", "approved" => 1),
array("name" =>"FONSECA, Edgar de Oliveira", "approved" => 1),
array("name" =>"FONYAT FILHO, José Bina", "approved" => 1),
array("name" =>"FORTE, Miguel", "approved" => 1),
array("name" =>"Forte-Gandolfi", "approved" => 1),
array("name" =>"FOUNDOUKAS, Marc Demetre", "approved" => 1),
array("name" =>"FOURNIÉ, Victor", "approved" => 1),
array("name" =>"FOX, Daniel Mackinson", "approved" => 1),
array("name" =>"FRAGELLI, Marcello Accioly", "approved" => 1),
array("name" =>"FRAGELLI, Marcelo Accioly", "approved" => 1),
array("name" =>"FRANÇA, Luiz da Penha", "approved" => 1),
array("name" =>"FRANCO, Luiz Roberto Carvalho", "approved" => 1),
array("name" =>"FRANCO, Pedro Augusto Vasques", "approved" => 1),
array("name" =>"FREITAS, Bernardo Casimiro de", "approved" => 1),
array("name" =>"FREITAS, Ernesto Sampaio", "approved" => 1),
array("name" =>"GALBINSKI, José", "approved" => 1),
array("name" =>"GALVÃO, Frei Antoniode Sant'Anna", "approved" => 1),
array("name" =>"GALVÃO, Raphael", "approved" => 1),
array("name" =>"GANDINO, Giácomo", "approved" => 1),
array("name" =>"GANDOLFI, José Maria", "approved" => 1),
array("name" =>"GANDOLFI, Roberto Luiz", "approved" => 1),
array("name" =>"GASPERINI, Gian Carlo", "approved" => 1),
array("name" =>"GAUDENZI, José Américo", "approved" => 1),
array("name" =>"GENNARO, João Eduardo de", "approved" => 1),
array("name" =>"GERARD, Marcelino", "approved" => 1),
array("name" =>"GIRE, Joseph ", "approved" => 1),
array("name" =>"GÓIS, Pero", "approved" => 1),
array("name" =>"Gomes de Almeida Fernandes", "approved" => 1),
array("name" =>"GOMES, Jose Cláudio", "approved" => 1),
array("name" =>"GONÇALVES, Cristóvão", "approved" => 1),
array("name" =>"GONÇALVES, Oswaldo Corrêa", "approved" => 1),
array("name" =>"GORDINHO, Antonieta Chaves Cintra", "approved" => 1),
array("name" =>"GOROVITZ, Matheus", "approved" => 1),
array("name" =>"GRINOVER, Lucio", "approved" => 1),
array("name" =>"GRUNEWALD, Heitor Rademaker", "approved" => 1),
array("name" =>"GUEDES SOBRINHO, Joaquim Manoel", "approved" => 1),
array("name" =>"GUILBERT, Albert", "approved" => 1),
array("name" =>"GUILLOBEL, Joaquim Cândido", "approved" => 1),
array("name" =>"GUSMÃO, Alexandre de", "approved" => 1),
array("name" =>"HANAOKA, Kazuo", "approved" => 1),
array("name" =>"HAUSSLER, Matheus", "approved" => 1),
array("name" =>"HEDBERG, Carl Gustav", "approved" => 1),
array("name" =>"HEEP, Adolf Franz", "approved" => 1),
array("name" =>"HEHL, Maximilian Emil", "approved" => 1),
array("name" =>"HERMAN, Luis Felipe Aflalo", "approved" => 1),
array("name" =>"Hidroservice Engenharia Ltda", "approved" => 1),
array("name" =>"IERVOLINO, Affonso", "approved" => 1),
array("name" =>"IMPÉRIO, Flávio", "approved" => 1),
array("name" =>"INDIO DA COSTA, Luiz Eduardo", "approved" => 1),
array("name" =>"Instituto de Orientação às Cooperativas Habitacionais de São Paulo (INOCOOP SP)", "approved" => 1),
array("name" =>"JACOME, Irmão Diogo", "approved" => 1),
array("name" =>"JÁCOME, Manuel Ferreira", "approved" => 1),
array("name" =>"JANNUZZI, Luís", "approved" => 1),
array("name" =>"JOBIM FILHO, Walter", "approved" => 1),
array("name" =>"JORDÃO, Elias Fausto Pacheco", "approved" => 1),
array("name" =>"JORGE, Wilson Edson", "approved" => 1),
array("name" =>"JULIANO, Miguel", "approved" => 1),
array("name" =>"JURADO, João Artacho", "approved" => 1),
array("name" =>"KAMIMURA, Massayoshi", "approved" => 1),
array("name" =>"KATINSKY, Julio Roberto", "approved" => 1),
array("name" =>"KLIASS, Rosa Grena Alembick", "approved" => 1),
array("name" =>"KOELER, Julius Friedrich", "approved" => 1),
array("name" =>"KOGAN, Mauricio", "approved" => 1),
array("name" =>"KORNGOLD, Lucjan", "approved" => 1),
array("name" =>"KRUG, George", "approved" => 1),
array("name" =>"KUHLMANN, Alberto", "approved" => 1),
array("name" =>"KURY, Eduardo", "approved" => 1),
array("name" =>"KUSAKA, Elza", "approved" => 1),
array("name" =>"LACERDA, Antonio de", "approved" => 1),
array("name" =>"LACERDA, Augusto Frederico de", "approved" => 1),
array("name" =>"LANDI, Antônio José", "approved" => 1),
array("name" =>"LEAL, Manuel Ferreira", "approved" => 1),
array("name" =>"LEÃO, Carlos de Azevedo", "approved" => 1),
array("name" =>"LEFÈVRE, José Eduardo de Assis", "approved" => 1),
array("name" =>"LEFÈVRE, Rodrigo Brotero", "approved" => 1),
array("name" =>"LEMOS, Carlos Alberto Cerqueira", "approved" => 1),
array("name" =>"LENCI, RENATO ", "approved" => 1),
array("name" =>"LEVI, Rino", "approved" => 1),
array("name" =>"LIBERAL, José Soares", "approved" => 1),
array("name" =>"LIBESKIND, David", "approved" => 1),
array("name" =>"LIEDERS, Michael", "approved" => 1),
array("name" =>"LIEUTHIER, Jean Louis", "approved" => 1),
array("name" =>"LIMA, Attílio Corrêa", "approved" => 1),
array("name" =>"LIMA, João da Gama Filgueiras", "approved" => 1),
array("name" =>"LIMA, José Porfírio de", "approved" => 1),
array("name" =>"LIMA, Richard", "approved" => 1),
array("name" =>"LINZ, Cristóvão", "approved" => 1),
array("name" =>"LISBOA, Antônio Francisco", "approved" => 1),
array("name" =>"LISBOA, Joaquim Miguel Ribeiro", "approved" => 1),
array("name" =>"LOHBAUER, Philipp", "approved" => 1),
array("name" =>"LONGO, Eduardo", "approved" => 1),
array("name" =>"LOPES, Humberto Lemos", "approved" => 1),
array("name" =>"LOTUFO, Vitor Amaral", "approved" => 1),
array("name" =>"LOTUFO, Zenon", "approved" => 1),
array("name" =>"LOURENÇO, Cesar Galha Bergstrom", "approved" => 1),
array("name" =>"LUÍS, Domingos", "approved" => 1),
array("name" =>"MACEDO, Josué", "approved" => 1),
array("name" =>"MACHADO, Lucio Gomes", "approved" => 1),
array("name" =>"MAGALHÃES JR., José", "approved" => 1),
array("name" =>"MAGALHÃES JÚNIOR, José", "approved" => 1),
array("name" =>"MAGALHÃES, Frei Gregório de", "approved" => 1),
array("name" =>"MAGALHÃES, José Francisco Xavier", "approved" => 1),
array("name" =>"MAGALHÃES, José Tibúrcio Pereira de", "approved" => 1),
array("name" =>"MAGALHÃES, Sérgio", "approved" => 1),
array("name" =>"MAGRO, Bruno Simões", "approved" => 1),
array("name" =>"MAITREJEAN, Jon Andoni Vergareche", "approved" => 1),
array("name" =>"MALAGRIDA, Gabriel", "approved" => 1),
array("name" =>"MANGE, Ernest Robert de Carvalho", "approved" => 1),
array("name" =>"MANSO, José Patrício da Silva", "approved" => 1),
array("name" =>"MARINHO, Hélio Ribas ", "approved" => 1),
array("name" =>"MARIUTTI, Germano", "approved" => 1),
array("name" =>"MARTIN, Jules", "approved" => 1),
array("name" =>"MARTINHO, Araken", "approved" => 1),
array("name" =>"MARTINO, Arnaldo Antonio", "approved" => 1),
array("name" =>"MARX, Roberto Burle", "approved" => 1),
array("name" =>"MATHIAS, Alfredo", "approved" => 1),
array("name" =>"MATOS, Antônio Fernandes de", "approved" => 1),
array("name" =>"MEDELLA, Roque Soares de", "approved" => 1),
array("name" =>"MELLO, Eduardo Augusto Kneese de", "approved" => 1),
array("name" =>"MELLO, Eduardo de Castro", "approved" => 1),
array("name" =>"MELLO, Ícaro de Castro", "approved" => 1),
array("name" =>"MELO, Frei Antonio Inácio do Coração de Jesus", "approved" => 1),
array("name" =>"MESQUITA, Arthur", "approved" => 1),
array("name" =>"MESQUITA, Francisco Frias da", "approved" => 1),
array("name" =>"MILA, Ariosto", "approved" => 1),
array("name" =>"MILLAN, Carlos Barjas", "approved" => 1),
array("name" =>"MILMAN, Iso", "approved" => 1),
array("name" =>"MINDLIN, Henrique Ephin", "approved" => 1),
array("name" =>"MIRANDA, Bento", "approved" => 1),
array("name" =>"MONTEIRO, Domingos José", "approved" => 1),
array("name" =>"MONTEIRO, Francisco da Nova", "approved" => 1),
array("name" =>"Monteiro, Heinsfurter & Rabinovitch", "approved" => 1),
array("name" =>"MONTESANO, Dario", "approved" => 1),
array("name" =>"MONTIGNY, Auguste Henri Victor Grandjean de", "approved" => 1),
array("name" =>"MORAES JÚNIOR, Luiz de", "approved" => 1),
array("name" =>"MORALES, Adolpho Rubio", "approved" => 1),
array("name" =>"MOREIRA, Jorge Machado", "approved" => 1),
array("name" =>"MORRISON, Walter Lawson", "approved" => 1),
array("name" =>"MOTTA, Carlos", "approved" => 1),
array("name" =>"MOURA, Luiz Eduardo Frias de", "approved" => 1),
array("name" =>"MOURA, Padre José de", "approved" => 1),
array("name" =>"MOURÃO, D. Luiz Antônio de Souza Botelho", "approved" => 1),
array("name" =>"MOYA, Antônio Garcia", "approved" => 1),
array("name" =>"MÜLLER, Daniel Pedro", "approved" => 1),
array("name" =>"MUMFORD, William", "approved" => 1),
array("name" =>"MURSA, Joaquim de Souza", "approved" => 1),
array("name" =>"MUYLAERT, Sandra", "approved" => 1),
array("name" =>"NAGAI, Satoru", "approved" => 1),
array("name" =>"NAVES, Carlos Alberto", "approved" => 1),
array("name" =>"NAVES, Cláudio", "approved" => 1),
array("name" =>"NEDDERMEYER, José Amaral ", "approved" => 1),
array("name" =>"NETTO, Antônio Augusto Antunes", "approved" => 1),
array("name" =>"NETTO, Domingos Theodoro de Azevedo", "approved" => 1),
array("name" =>"NETTO, Luiz Forte", "approved" => 1),
array("name" =>"NETTO, Marcos Konder", "approved" => 1),
array("name" =>"NETTO, Wilson Reis", "approved" => 1),
array("name" =>"NEVES, Christiano Stockler das", "approved" => 1),
array("name" =>"NEVES, José Maria da Silva", "approved" => 1),
array("name" =>"NEVES, Júlio José Franco", "approved" => 1),
array("name" =>"NIEMEYER, Oscar Ribeiro de Almeida de", "approved" => 1),
array("name" =>"NIGRIELLO, Andreína", "approved" => 1),
array("name" =>"NÓBREGA, Padre Manuel da", "approved" => 1),
array("name" =>"NOGUEIRA, Irmão Mateus", "approved" => 1),
array("name" =>"NOGUEIRA, José Mario", "approved" => 1),
array("name" =>"NOGUEIRA, Mauro Luiz Neves", "approved" => 1),
array("name" =>"NOZU, Sérgio", "approved" => 1),
array("name" =>"NUNES, Padre Leonardo", "approved" => 1),
array("name" =>"OHTAKE, Ruy Massashi", "approved" => 1),
array("name" =>"OLIVEIRA, Marcial Fleury de", "approved" => 1),
array("name" =>"OLIVEIRA, Sidney de ", "approved" => 1),
array("name" =>"Ottoni Arquitetos Associados", "approved" => 1),
array("name" =>"OTTONI, David Araujo Benedito", "approved" => 1),
array("name" =>"OURIQUE, José Jacquesda Costa", "approved" => 1),
array("name" =>"PACHECO, Tércio Fontana", "approved" => 1),
array("name" =>"PADOVANO, Bruno Roberto", "approved" => 1),
array("name" =>"PAES, Garcia Rodrigues", "approved" => 1),
array("name" =>"PAIS, Fernão Dias", "approved" => 1),
array("name" =>"PALANTI, Giancarlo", "approved" => 1),
array("name" =>"PALLAMIN, Vera Maria", "approved" => 1),
array("name" =>"PASSOS, Francisco de Oliveira", "approved" => 1),
array("name" =>"PASTA, Hélio", "approved" => 1),
array("name" =>"PENNA, Herculano Velloso Ferreira", "approved" => 1),
array("name" =>"PENNA, Ivo de Azevedo", "approved" => 1),
array("name" =>"PENTEADO, Hélio Maria", "approved" => 1),
array("name" =>"PENTEADO, Hernani do Val", "approved" => 1),
array("name" =>"PEREIRA, Manoel", "approved" => 1),
array("name" =>"PEREIRA, Miguel Alves", "approved" => 1),
array("name" =>"PEREIRA, Sérgio Ferro", "approved" => 1),
array("name" =>"PERRONE, Rafael Antônio Cunha", "approved" => 1),
array("name" =>"PEYRONTON, Charles", "approved" => 1),
array("name" =>"PEYROTON, Charles", "approved" => 1),
array("name" =>"PFISTERER, Peter", "approved" => 1),
array("name" =>"PICCHI, Atílio", "approved" => 1),
array("name" =>"PICCHIA, Paulo Celso del", "approved" => 1),
array("name" =>"PICCOLO, Douglas et al", "approved" => 1),
array("name" =>"PILON, Jacques Emile Paul", "approved" => 1),
array("name" =>"PIMENTEL, Fernando Manoel de Souza Costa Freire", "approved" => 1),
array("name" =>"PINOTTI, Ferrucio Julio", "approved" => 1),
array("name" =>"PINTO, José de Almeida", "approved" => 1),
array("name" =>"PIRES, Padre Antônio", "approved" => 1),
array("name" =>"PIRES, Salvador", "approved" => 1),
array("name" =>"PITOMBO, Antônio Carlos de Moraes", "approved" => 1),
array("name" =>"Polizotto S/A Serralheria Artística e Ind. Ltda", "approved" => 1),
array("name" =>"PORTO, Sidônio", "approved" => 1),
array("name" =>"PRADO, Amador Cintra do", "approved" => 1),
array("name" =>"PRADO, Diogo Benedito dos Santos", "approved" => 1),
array("name" =>"PRESTES MAIA, Francisco", "approved" => 1),
array("name" =>"PRETO, Manuel", "approved" => 1),
array("name" =>"Projecon Soc. Civil Ltda.", "approved" => 1),
array("name" =>"PUCCI, Luigi", "approved" => 1),
array("name" =>"PUJOL JÚNIOR, Hippolyto Gustavo", "approved" => 1),
array("name" =>"PUJOL, Hippolyto Gustavo", "approved" => 1),
array("name" =>"PUTTKAMER, Hermann von", "approved" => 1),
array("name" =>"RAMALHO JÚNIOR, Joel ", "approved" => 1),
array("name" =>"RAMOS DE AZEVEDO, Francisco de Paula ", "approved" => 1),
array("name" =>"RAMOS, Jorge Wilheim", "approved" => 1),
array("name" =>"RAMOS, Waldir", "approved" => 1),
array("name" =>"RANZINI, Felisberto", "approved" => 1),
array("name" =>"RATH, Carlos Friedrich Josef", "approved" => 1),
array("name" =>"REAL, João de Macedo Corte", "approved" => 1),
array("name" =>"REBELO, José Maria Jacinto", "approved" => 1),
array("name" =>"REBOUÇAS FILHO, Antônio Pereira", "approved" => 1),
array("name" =>"REBOUÇAS, Diógenes de Almeida", "approved" => 1),
array("name" =>"REGO, Flávio Marinho", "approved" => 1),
array("name" =>"REIDY, Affonso Eduardo", "approved" => 1),
array("name" =>"REINACH, Henrique de Castro", "approved" => 1),
array("name" =>"REIS FILHO, Nestor Goulart", "approved" => 1),
array("name" =>"REIS, Francisco de Assis Couto dos", "approved" => 1),
array("name" =>"REIS, José de Souza", "approved" => 1),
array("name" =>"RENDU, Auguste", "approved" => 1),
array("name" =>"RÉVY, Jean", "approved" => 1),
array("name" =>"RIBEIRO, Mário", "approved" => 1),
array("name" =>"RIBEIRO, Paulo Antunes", "approved" => 1),
array("name" =>"Rino Levi Arquitetos Associados Ltda", "approved" => 1),
array("name" =>"RISI JÚNIOR, Affonso", "approved" => 1),
array("name" =>"ROBERTO, Marcelo", "approved" => 1),
array("name" =>"ROBERTO, Maurício", "approved" => 1),
array("name" =>"ROBERTO, Milton", "approved" => 1),
array("name" =>"ROBERTS, William Milnor", "approved" => 1),
array("name" =>"ROCHA, Manuel dos Reis Pinto da", "approved" => 1),
array("name" =>"ROCHA, Paulo Archias Mendes da", "approved" => 1),
array("name" =>"RODRIGUES, Augusto", "approved" => 1),
array("name" =>"RODRIGUES, Eduardo de Jesus", "approved" => 1),
array("name" =>"RODRIGUES, Irmão Vicente", "approved" => 1),
array("name" =>"RODRIGUES, Jayme Campello Fonseca", "approved" => 1),
array("name" =>"RODRIGUES, Lúcio Martins", "approved" => 1),
array("name" =>"ROLLA, Joaquim", "approved" => 1),
array("name" =>"ROMIEU, Charles", "approved" => 1),
array("name" =>"Rosa Grena Kliass Paisag., Planej. e Projetos Ltda", "approved" => 1),
array("name" =>"ROSÁRIO, Frei Luiz do", "approved" => 1),
array("name" =>"ROSSI, Cláudio", "approved" => 1),
array("name" =>"ROSSI, Domiziano", "approved" => 1),
array("name" =>"ROZA, Ary Garcia", "approved" => 1),
array("name" =>"RUCHTI, Jacob Mauricio ", "approved" => 1),
array("name" =>"RUCHTI, Karl Friedrich", "approved" => 1),
array("name" =>"RUDGE, Guilherme Maxwell", "approved" => 1),
array("name" =>"SABÓIA E SILVA, Domingos Sérgio", "approved" => 1),
array("name" =>"SACK, Werner", "approved" => 1),
array("name" =>"SAIA, Luís", "approved" => 1),
array("name" =>"SALDANHA, Manuel Cardoso de", "approved" => 1),
array("name" =>"SALTINI, Giulio", "approved" => 1),
array("name" =>"SALVADOR, Frei Simão do", "approved" => 1),
array("name" =>"SANOVICZ, Abrahão Velvu", "approved" => 1),
array("name" =>"SANTA MARIA, Frei Manuel de", "approved" => 1),
array("name" =>"SANTOS, Fernando César Belloube dos", "approved" => 1),
array("name" =>"SANTOS, Francisco dos", "approved" => 1),
array("name" =>"SÃO BENTO, Bernardo de ", "approved" => 1),
array("name" =>"SÃO FRANCISCO, Frei Miguel", "approved" => 1),
array("name" =>"SÃO JOÃO, Macário de ", "approved" => 1),
array("name" =>"SÃO PAULO, Frei Antônio de", "approved" => 1),
array("name" =>"SARAIVA, Pedro Paulo de Mello", "approved" => 1),
array("name" =>"SAUER, Arthur", "approved" => 1),
array("name" =>"SAWAYA, Sylvio Barros", "approved" => 1),
array("name" =>"SEGNINI JUNIOR, Francisco", "approved" => 1),
array("name" =>"SEVERO, Ricardo", "approved" => 1),
array("name" =>"SHARP, Robert", "approved" => 1),
array("name" =>"SICILIANO, Heribaldo", "approved" => 1),
array("name" =>"SIEVERS, Ricardo", "approved" => 1),
array("name" =>"SILVA, Luiz José Gonçalvez da", "approved" => 1),
array("name" =>"SILVA, Miguel Juliano e", "approved" => 1),
array("name" =>"SIMÕES, José Roberto Leme", "approved" => 1),
array("name" =>"SIQUEIRA, D. Ângela de", "approved" => 1),
array("name" =>"SIQUEIRA, D. Leonor de", "approved" => 1),
array("name" =>"SOARES, Oscar Ribeiro de Almeida de Niemeyer", "approved" => 1),
array("name" =>"SÓCRATES, Jodete Rios", "approved" => 1),
array("name" =>"SOUTO, Mário Salles", "approved" => 1),
array("name" =>"SOUZA, Abelardo Reidy de", "approved" => 1),
array("name" =>"SOUZA, Antonio Francisco de Paula", "approved" => 1),
array("name" =>"SOUZA, Jorge Félix de", "approved" => 1),
array("name" =>"SOUZA, Luiz", "approved" => 1),
array("name" =>"SOUZA, Mário Rodrigue de", "approved" => 1),
array("name" =>"SOUZA, Martim Afonso de", "approved" => 1),
array("name" =>"SOUZA, Tomé de", "approved" => 1),
array("name" =>"SOUZA, Wladimir Alves de", "approved" => 1),
array("name" =>"STEVAUX, Eusébio", "approved" => 1),
array("name" =>"SZPIGEL, Samuel", "approved" => 1),
array("name" =>"TALAAT, Alfred", "approved" => 1),
array("name" =>"TAMAKI, Waldemar Teru", "approved" => 1),
array("name" =>"TEBAS, Joaquim Pinto de Oliveira", "approved" => 1),
array("name" =>"TEIXEIRA, Frei Mauro", "approved" => 1),
array("name" =>"TELLES, Armando Carlos da Silva", "approved" => 1),
array("name" =>"TELLES, Francisco Teixeira da Silva", "approved" => 1),
array("name" =>"TELLES, Jayme da Silva", "approved" => 1),
array("name" =>"TERESA, Manoel de Santa", "approved" => 1),
array("name" =>"THIVIER, Eugéne", "approved" => 1),
array("name" =>"TIBAU, Roberto J. Goulart", "approved" => 1),
array("name" =>"TIBAU, Roberto José Goulart", "approved" => 1),
array("name" =>"TIBIRIÇÁ, Martim Afonso", "approved" => 1),
array("name" =>"TOLEDO, Aldary Henrique", "approved" => 1),
array("name" =>"TOLEDO, Augusto de", "approved" => 1),
array("name" =>"TOSCANO, João Walter", "approved" => 1),
array("name" =>"TOSCANO, Odiléa Helena Setti", "approved" => 1),
array("name" =>"TREZZA, Nelson", "approved" => 1),
array("name" =>"VAL, João Gomes do", "approved" => 1),
array("name" =>"VALDETARO, Oscar", "approved" => 1),
array("name" =>"VALIM, Manoel de Aguilar", "approved" => 1),
array("name" =>"VALORI, Giuseppe", "approved" => 1),
array("name" =>"VARNHAGEN, Friedrich Ludwig Wilheim von", "approved" => 1),
array("name" =>"VASCONCELLOS, Ernani Mendes de", "approved" => 1),
array("name" =>"VAUTHIER, Louis Léger", "approved" => 1),
array("name" =>"VELOSO, Diogo da Silveira", "approved" => 1),
array("name" =>"VENCHIARUTTI, Vasco Antonio ", "approved" => 1),
array("name" =>"VERJOVSKY, Olga", "approved" => 1),
array("name" =>"VIANNA, Raymundo", "approved" => 1),
array("name" =>"VIANNA, Rubens Carneiro", "approved" => 1),
array("name" =>"VILLANOVA, Aurélio", "approved" => 1),
array("name" =>"VILLAVECCHIA, Luigi", "approved" => 1),
array("name" =>"VILLEGAIGNON, Nicolau Durand de", "approved" => 1),
array("name" =>"VIVEIROS, José de", "approved" => 1),
array("name" =>"WAEHNELDT, Carl Friedrich Gustav ", "approved" => 1),
array("name" =>"Waldemar Cordeiro Paisag., Planej. e Projetos Ltda.", "approved" => 1),
array("name" =>"WARCHAVCHIK, Gregori Ilych ", "approved" => 1),
array("name" =>"WEISCHENCK, Guilherme Benjamin", "approved" => 1),
array("name" =>"WILHEIM, Jorge", "approved" => 1),
array("name" =>"WINTER, Guilherme Ernesto", "approved" => 1),
array("name" =>"WYZENSKI, Cristino", "approved" => 1),
array("name" =>"YURGEL, Marlene", "approved" => 1),
array("name" =>"ZALSZUPIN, Jorge", "approved" => 1),
array("name" =>"ZANETTINI, Siegbert ", "approved" => 1),
array("name" =>"ZEIGER, Jayme", "approved" => 1),
array("name" =>"ZIMBRES, Paulo de Melo", "approved" => 1),
array("name" =>"ZMEKHOL, Roger", "approved" => 1),
array("name" =>"ZOLKO, Gregório ", "approved" => 1),
		));

	}

	/**
	 * Reverse the migrations.
	 *
	 * @return void
	 */
	public function down()
	{
		//DB::table('authors')->where('approved', '=', 1)->delete();
	}

}
