<?php

use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

class FillListAllAcervoTagsTable extends Migration {

	/**
	 * Run the migrations.
	 *
	 * @return void
	 */
	public function up()
	{
		DB::table('tags')->insert(    		array(
    		array("name" =>"ábaco", "count" => 0, "type" =>"Acervo"),
    		array("name" =>"abadia", "count" => 0, "type" =>"Acervo"),
    		array("name" =>"abegoaria", "count" => 0, "type" =>"Acervo"),
    		array("name" =>"abertura", "count" => 0, "type" =>"Acervo"),
    		array("name" =>"abertura zenital", "count" => 0, "type" =>"Acervo"),
    		array("name" =>"abóbada", "count" => 0, "type" =>"Acervo"),
    		array("name" =>"abóbada de berço", "count" => 0, "type" =>"Acervo"),
    		array("name" =>"abraçadeira", "count" => 0, "type" =>"Acervo"),
    		array("name" =>"abside", "count" => 0, "type" =>"Acervo"),
    		array("name" =>"acéquia", "count" => 0, "type" =>"Acervo"),
    		array("name" =>"aço", "count" => 0, "type" =>"Acervo"),
    		array("name" =>"aço inoxidável ", "count" => 0, "type" =>"Acervo"),
    		array("name" =>"acrotério", "count" => 0, "type" =>"Acervo"),
    		array("name" =>"adobe", "count" => 0, "type" =>"Acervo"),
    		array("name" =>"adro", "count" => 0, "type" =>"Acervo"),
    		array("name" =>"aeroporto ", "count" => 0, "type" =>"Acervo"),
    		array("name" =>"agência bancária", "count" => 0, "type" =>"Acervo"),
    		array("name" =>"agência de viagens", "count" => 0, "type" =>"Acervo"),
    		array("name" =>"aglomerado", "count" => 0, "type" =>"Acervo"),
    		array("name" =>"alabastro", "count" => 0, "type" =>"Acervo"),
    		array("name" =>"alambrado", "count" => 0, "type" =>"Acervo"),
    		array("name" =>"alçapão", "count" => 0, "type" =>"Acervo"),
    		array("name" =>"alfândega", "count" => 0, "type" =>"Acervo"),
    		array("name" =>"algibe", "count" => 0, "type" =>"Acervo"),
    		array("name" =>"alojamento", "count" => 0, "type" =>"Acervo"),
    		array("name" =>"alpendre", "count" => 0, "type" =>"Acervo"),
    		array("name" =>"altar", "count" => 0, "type" =>"Acervo"),
    		array("name" =>"alto relevo", "count" => 0, "type" =>"Acervo"),
    		array("name" =>"alumínio ", "count" => 0, "type" =>"Acervo"),
    		array("name" =>"alvenaria ", "count" => 0, "type" =>"Acervo"),
    		array("name" =>"amianto ", "count" => 0, "type" =>"Acervo"),
    		array("name" =>"andaime", "count" => 0, "type" =>"Acervo"),
    		array("name" =>"anel de concreto ", "count" => 0, "type" =>"Acervo"),
    		array("name" =>"aprisco", "count" => 0, "type" =>"Acervo"),
    		array("name" =>"aquecedor", "count" => 0, "type" =>"Acervo"),
    		array("name" =>"ar condicionado", "count" => 0, "type" =>"Acervo"),
    		array("name" =>"arcada", "count" => 0, "type" =>"Acervo"),
    		array("name" =>"arco", "count" => 0, "type" =>"Acervo"),
    		array("name" =>"arco abatido", "count" => 0, "type" =>"Acervo"),
    		array("name" =>"arco ogival", "count" => 0, "type" =>"Acervo"),
    		array("name" =>"arco pleno", "count" => 0, "type" =>"Acervo"),
    		array("name" =>"área de serviço", "count" => 0, "type" =>"Acervo"),
    		array("name" =>"areia", "count" => 0, "type" =>"Acervo"),
    		array("name" =>"argamassa", "count" => 0, "type" =>"Acervo"),
    		array("name" =>"argamassa armada", "count" => 0, "type" =>"Acervo"),
    		array("name" =>"argila", "count" => 0, "type" =>"Acervo"),
    		array("name" =>"armadura", "count" => 0, "type" =>"Acervo"),
    		array("name" =>"armadura metálica", "count" => 0, "type" =>"Acervo"),
    		array("name" =>"arquibancada", "count" => 0, "type" =>"Acervo"),
    		array("name" =>"arquitrave", "count" => 0, "type" =>"Acervo"),
    		array("name" =>"arsenal", "count" => 0, "type" =>"Acervo"),
    		array("name" =>"atelier", "count" => 0, "type" =>"Acervo"),
    		array("name" =>"ático", "count" => 0, "type" =>"Acervo"),
    		array("name" =>"átrio", "count" => 0, "type" =>"Acervo"),
    		array("name" =>"auditório", "count" => 0, "type" =>"Acervo"),
    		array("name" =>"azulejo", "count" => 0, "type" =>"Acervo"),
    		array("name" =>"baixo relevo", "count" => 0, "type" =>"Acervo"),
    		array("name" =>"balaustrada", "count" => 0, "type" =>"Acervo"),
    		array("name" =>"balaústre", "count" => 0, "type" =>"Acervo"),
    		array("name" =>"balcão", "count" => 0, "type" =>"Acervo"),
    		array("name" =>"baldrame", "count" => 0, "type" =>"Acervo"),
    		array("name" =>"bambu", "count" => 0, "type" =>"Acervo"),
    		array("name" =>"banca de jornal", "count" => 0, "type" =>"Acervo"),
    		array("name" =>"bancada", "count" => 0, "type" =>"Acervo"),
    		array("name" =>"banco ", "count" => 0, "type" =>"Acervo"),
    		array("name" =>"bandeira", "count" => 0, "type" =>"Acervo"),
    		array("name" =>"banheiro", "count" => 0, "type" =>"Acervo"),
    		array("name" =>"bar", "count" => 0, "type" =>"Acervo"),
    		array("name" =>"barda", "count" => 0, "type" =>"Acervo"),
    		array("name" =>"barra de contenção", "count" => 0, "type" =>"Acervo"),
    		array("name" =>"barraco", "count" => 0, "type" =>"Acervo"),
    		array("name" =>"barragem", "count" => 0, "type" =>"Acervo"),
    		array("name" =>"barro", "count" => 0, "type" =>"Acervo"),
    		array("name" =>"barro cozido ", "count" => 0, "type" =>"Acervo"),
    		array("name" =>"basílica", "count" => 0, "type" =>"Acervo"),
    		array("name" =>"beiral ", "count" => 0, "type" =>"Acervo"),
    		array("name" =>"biblioteca ", "count" => 0, "type" =>"Acervo"),
    		array("name" =>"bloco de concreto ", "count" => 0, "type" =>"Acervo"),
    		array("name" =>"bloco de pedra", "count" => 0, "type" =>"Acervo"),
    		array("name" =>"bloco de vidro ", "count" => 0, "type" =>"Acervo"),
    		array("name" =>"bloco intertravado", "count" => 0, "type" =>"Acervo"),
    		array("name" =>"borracha", "count" => 0, "type" =>"Acervo"),
    		array("name" =>"brise", "count" => 0, "type" =>"Acervo"),
    		array("name" =>"brita ", "count" => 0, "type" =>"Acervo"),
    		array("name" =>"bronze", "count" => 0, "type" =>"Acervo"),
    		array("name" =>"cachorro ", "count" => 0, "type" =>"Acervo"),
    		array("name" =>"caibro", "count" => 0, "type" =>"Acervo"),
    		array("name" =>"caixa d'água", "count" => 0, "type" =>"Acervo"),
    		array("name" =>"caixilho", "count" => 0, "type" =>"Acervo"),
    		array("name" =>"cal", "count" => 0, "type" =>"Acervo"),
    		array("name" =>"cal preta", "count" => 0, "type" =>"Acervo"),
    		array("name" =>"cal terçada ", "count" => 0, "type" =>"Acervo"),
    		array("name" =>"calçada", "count" => 0, "type" =>"Acervo"),
    		array("name" =>"calcário", "count" => 0, "type" =>"Acervo"),
    		array("name" =>"calha", "count" => 0, "type" =>"Acervo"),
    		array("name" =>"câmara", "count" => 0, "type" =>"Acervo"),
    		array("name" =>"camping", "count" => 0, "type" =>"Acervo"),
    		array("name" =>"campo de futebol ", "count" => 0, "type" =>"Acervo"),
    		array("name" =>"canal ", "count" => 0, "type" =>"Acervo"),
    		array("name" =>"canal de drenagem", "count" => 0, "type" =>"Acervo"),
    		array("name" =>"canteiro de obras", "count" => 0, "type" =>"Acervo"),
    		array("name" =>"capela", "count" => 0, "type" =>"Acervo"),
    		array("name" =>"capela-mor", "count" => 0, "type" =>"Acervo"),
    		array("name" =>"capitel", "count" => 0, "type" =>"Acervo"),
    		array("name" =>"cariátide", "count" => 0, "type" =>"Acervo"),
    		array("name" =>"carpete", "count" => 0, "type" =>"Acervo"),
    		array("name" =>"cascalho", "count" => 0, "type" =>"Acervo"),
    		array("name" =>"catedral", "count" => 0, "type" =>"Acervo"),
    		array("name" =>"cemitério", "count" => 0, "type" =>"Acervo"),
    		array("name" =>"centro cívico", "count" => 0, "type" =>"Acervo"),
    		array("name" =>"centro cultural", "count" => 0, "type" =>"Acervo"),
    		array("name" =>"centro de convenções", "count" => 0, "type" =>"Acervo"),
    		array("name" =>"centro de saúde", "count" => 0, "type" =>"Acervo"),
    		array("name" =>"cerâmica", "count" => 0, "type" =>"Acervo"),
    		array("name" =>"cerca", "count" => 0, "type" =>"Acervo"),
    		array("name" =>"cerca viva", "count" => 0, "type" =>"Acervo"),
    		array("name" =>"chaminé", "count" => 0, "type" =>"Acervo"),
    		array("name" =>"cimbramento", "count" => 0, "type" =>"Acervo"),
    		array("name" =>"cimento", "count" => 0, "type" =>"Acervo"),
    		array("name" =>"cinema", "count" => 0, "type" =>"Acervo"),
    		array("name" =>"clarabóia", "count" => 0, "type" =>"Acervo"),
    		array("name" =>"clínica", "count" => 0, "type" =>"Acervo"),
    		array("name" =>"clube", "count" => 0, "type" =>"Acervo"),
    		array("name" =>"cobertura", "count" => 0, "type" =>"Acervo"),
    		array("name" =>"cobogó ", "count" => 0, "type" =>"Acervo"),
    		array("name" =>"colégio ", "count" => 0, "type" =>"Acervo"),
    		array("name" =>"coluna", "count" => 0, "type" =>"Acervo"),
    		array("name" =>"colunata", "count" => 0, "type" =>"Acervo"),
    		array("name" =>"comercial", "count" => 0, "type" =>"Acervo"),
    		array("name" =>"comunicação", "count" => 0, "type" =>"Acervo"),
    		array("name" =>"concreto", "count" => 0, "type" =>"Acervo"),
    		array("name" =>"concreto aparente", "count" => 0, "type" =>"Acervo"),
    		array("name" =>"concreto armado", "count" => 0, "type" =>"Acervo"),
    		array("name" =>"concreto pintado", "count" => 0, "type" =>"Acervo"),
    		array("name" =>"concreto queimado", "count" => 0, "type" =>"Acervo"),
    		array("name" =>"conduíte", "count" => 0, "type" =>"Acervo"),
    		array("name" =>"confeitaria", "count" => 0, "type" =>"Acervo"),
    		array("name" =>"conjunto habitacional", "count" => 0, "type" =>"Acervo"),
    		array("name" =>"contraverga", "count" => 0, "type" =>"Acervo"),
    		array("name" =>"coreto", "count" => 0, "type" =>"Acervo"),
    		array("name" =>"cornija", "count" => 0, "type" =>"Acervo"),
    		array("name" =>"corredor", "count" => 0, "type" =>"Acervo"),
    		array("name" =>"córrego", "count" => 0, "type" =>"Acervo"),
    		array("name" =>"corrimão", "count" => 0, "type" =>"Acervo"),
    		array("name" =>"cortiça", "count" => 0, "type" =>"Acervo"),
    		array("name" =>"cortiço", "count" => 0, "type" =>"Acervo"),
    		array("name" =>"cozinha", "count" => 0, "type" =>"Acervo"),
    		array("name" =>"creche", "count" => 0, "type" =>"Acervo"),
    		array("name" =>"cumeeira", "count" => 0, "type" =>"Acervo"),
    		array("name" =>"cúpula", "count" => 0, "type" =>"Acervo"),
    		array("name" =>"deck", "count" => 0, "type" =>"Acervo"),
    		array("name" =>"degrau", "count" => 0, "type" =>"Acervo"),
    		array("name" =>"desnível", "count" => 0, "type" =>"Acervo"),
    		array("name" =>"divisória", "count" => 0, "type" =>"Acervo"),
    		array("name" =>"domus", "count" => 0, "type" =>"Acervo"),
    		array("name" =>"dormitório", "count" => 0, "type" =>"Acervo"),
    		array("name" =>"drywall", "count" => 0, "type" =>"Acervo"),
    		array("name" =>"duto de ar", "count" => 0, "type" =>"Acervo"),
    		array("name" =>"educacional", "count" => 0, "type" =>"Acervo"),
    		array("name" =>"elemento vazado ", "count" => 0, "type" =>"Acervo"),
    		array("name" =>"elevador ", "count" => 0, "type" =>"Acervo"),
    		array("name" =>"embaixada", "count" => 0, "type" =>"Acervo"),
    		array("name" =>"empena", "count" => 0, "type" =>"Acervo"),
    		array("name" =>"encosta", "count" => 0, "type" =>"Acervo"),
    		array("name" =>"enxaimel", "count" => 0, "type" =>"Acervo"),
    		array("name" =>"epóxi", "count" => 0, "type" =>"Acervo"),
    		array("name" =>"escada", "count" => 0, "type" =>"Acervo"),
    		array("name" =>"escada caracol", "count" => 0, "type" =>"Acervo"),
    		array("name" =>"escada de mão", "count" => 0, "type" =>"Acervo"),
    		array("name" =>"escada rolante", "count" => 0, "type" =>"Acervo"),
    		array("name" =>"escadaria", "count" => 0, "type" =>"Acervo"),
    		array("name" =>"escadaria", "count" => 0, "type" =>"Acervo"),
    		array("name" =>"escola", "count" => 0, "type" =>"Acervo"),
    		array("name" =>"escora", "count" => 0, "type" =>"Acervo"),
    		array("name" =>"escritório", "count" => 0, "type" =>"Acervo"),
    		array("name" =>"escultura ", "count" => 0, "type" =>"Acervo"),
    		array("name" =>"espelho", "count" => 0, "type" =>"Acervo"),
    		array("name" =>"espelho d'água", "count" => 0, "type" =>"Acervo"),
    		array("name" =>"esportivo", "count" => 0, "type" =>"Acervo"),
    		array("name" =>"esquadria", "count" => 0, "type" =>"Acervo"),
    		array("name" =>"esquina", "count" => 0, "type" =>"Acervo"),
    		array("name" =>"estaca", "count" => 0, "type" =>"Acervo"),
    		array("name" =>"estaca", "count" => 0, "type" =>"Acervo"),
    		array("name" =>"estação de trem", "count" => 0, "type" =>"Acervo"),
    		array("name" =>"estação rodoviária", "count" => 0, "type" =>"Acervo"),
    		array("name" =>"estacionamento", "count" => 0, "type" =>"Acervo"),
    		array("name" =>"esteio", "count" => 0, "type" =>"Acervo"),
    		array("name" =>"estrada", "count" => 0, "type" =>"Acervo"),
    		array("name" =>"estrutura em balanço", "count" => 0, "type" =>"Acervo"),
    		array("name" =>"estúdio ", "count" => 0, "type" =>"Acervo"),
    		array("name" =>"estufa", "count" => 0, "type" =>"Acervo"),
    		array("name" =>"exaustor", "count" => 0, "type" =>"Acervo"),
    		array("name" =>"exposição", "count" => 0, "type" =>"Acervo"),
    		array("name" =>"fábrica", "count" => 0, "type" =>"Acervo"),
    		array("name" =>"fachada", "count" => 0, "type" =>"Acervo"),
    		array("name" =>"fachada cega", "count" => 0, "type" =>"Acervo"),
    		array("name" =>"fachada de vidro ", "count" => 0, "type" =>"Acervo"),
    		array("name" =>"faculdade", "count" => 0, "type" =>"Acervo"),
    		array("name" =>"ferro", "count" => 0, "type" =>"Acervo"),
    		array("name" =>"fibrocimento", "count" => 0, "type" =>"Acervo"),
    		array("name" =>"fonte", "count" => 0, "type" =>"Acervo"),
    		array("name" =>"forma", "count" => 0, "type" =>"Acervo"),
    		array("name" =>"forro", "count" => 0, "type" =>"Acervo"),
    		array("name" =>"forro nervurado", "count" => 0, "type" =>"Acervo"),
    		array("name" =>"friso", "count" => 0, "type" =>"Acervo"),
    		array("name" =>"frontão", "count" => 0, "type" =>"Acervo"),
    		array("name" =>"galeria", "count" => 0, "type" =>"Acervo"),
    		array("name" =>"galpão", "count" => 0, "type" =>"Acervo"),
    		array("name" =>"garagem", "count" => 0, "type" =>"Acervo"),
    		array("name" =>"gárgula", "count" => 0, "type" =>"Acervo"),
    		array("name" =>"gesso", "count" => 0, "type" =>"Acervo"),
    		array("name" =>"ginásio", "count" => 0, "type" =>"Acervo"),
    		array("name" =>"grade", "count" => 0, "type" =>"Acervo"),
    		array("name" =>"granilite", "count" => 0, "type" =>"Acervo"),
    		array("name" =>"granito", "count" => 0, "type" =>"Acervo"),
    		array("name" =>"guarda corpo", "count" => 0, "type" =>"Acervo"),
    		array("name" =>"habitação", "count" => 0, "type" =>"Acervo"),
    		array("name" =>"hall", "count" => 0, "type" =>"Acervo"),
    		array("name" =>"hangar", "count" => 0, "type" =>"Acervo"),
    		array("name" =>"haste", "count" => 0, "type" =>"Acervo"),
    		array("name" =>"hipódromo", "count" => 0, "type" =>"Acervo"),
    		array("name" =>"holofote", "count" => 0, "type" =>"Acervo"),
    		array("name" =>"hospital ", "count" => 0, "type" =>"Acervo"),
    		array("name" =>"hotel", "count" => 0, "type" =>"Acervo"),
    		array("name" =>"igreja", "count" => 0, "type" =>"Acervo"),
    		array("name" =>"industrial", "count" => 0, "type" =>"Acervo"),
    		array("name" =>"janela ", "count" => 0, "type" =>"Acervo"),
    		array("name" =>"janela basculante", "count" => 0, "type" =>"Acervo"),
    		array("name" =>"janela contrapeso", "count" => 0, "type" =>"Acervo"),
    		array("name" =>"janela de correr", "count" => 0, "type" =>"Acervo"),
    		array("name" =>"janela guilhotinada", "count" => 0, "type" =>"Acervo"),
    		array("name" =>"janela pivotante", "count" => 0, "type" =>"Acervo"),
    		array("name" =>"janelas duas folhas", "count" => 0, "type" =>"Acervo"),
    		array("name" =>"jardim", "count" => 0, "type" =>"Acervo"),
    		array("name" =>"laboratório", "count" => 0, "type" =>"Acervo"),
    		array("name" =>"ladrilho", "count" => 0, "type" =>"Acervo"),
    		array("name" =>"lago", "count" => 0, "type" =>"Acervo"),
    		array("name" =>"lagoa", "count" => 0, "type" =>"Acervo"),
    		array("name" =>"laje", "count" => 0, "type" =>"Acervo"),
    		array("name" =>"laje nervurada", "count" => 0, "type" =>"Acervo"),
    		array("name" =>"lajota", "count" => 0, "type" =>"Acervo"),
    		array("name" =>"lanchonete", "count" => 0, "type" =>"Acervo"),
    		array("name" =>"lanternim ", "count" => 0, "type" =>"Acervo"),
    		array("name" =>"lareira", "count" => 0, "type" =>"Acervo"),
    		array("name" =>"largo", "count" => 0, "type" =>"Acervo"),
    		array("name" =>"latrina", "count" => 0, "type" =>"Acervo"),
    		array("name" =>"lavanderia", "count" => 0, "type" =>"Acervo"),
    		array("name" =>"linha férrea", "count" => 0, "type" =>"Acervo"),
    		array("name" =>"loja", "count" => 0, "type" =>"Acervo"),
    		array("name" =>"lona", "count" => 0, "type" =>"Acervo"),
    		array("name" =>"luminária", "count" => 0, "type" =>"Acervo"),
    		array("name" =>"madeira", "count" => 0, "type" =>"Acervo"),
    		array("name" =>"madeira compensada", "count" => 0, "type" =>"Acervo"),
    		array("name" =>"mão francesa", "count" => 0, "type" =>"Acervo"),
    		array("name" =>"maquinário", "count" => 0, "type" =>"Acervo"),
    		array("name" =>"mar", "count" => 0, "type" =>"Acervo"),
    		array("name" =>"mares de morros ", "count" => 0, "type" =>"Acervo"),
    		array("name" =>"mármore", "count" => 0, "type" =>"Acervo"),
    		array("name" =>"marquise ", "count" => 0, "type" =>"Acervo"),
    		array("name" =>"massa corrida", "count" => 0, "type" =>"Acervo"),
    		array("name" =>"mastro", "count" => 0, "type" =>"Acervo"),
    		array("name" =>"mausoléu ", "count" => 0, "type" =>"Acervo"),
    		array("name" =>"mercado", "count" => 0, "type" =>"Acervo"),
    		array("name" =>"mesquita", "count" => 0, "type" =>"Acervo"),
    		array("name" =>"mezanino ", "count" => 0, "type" =>"Acervo"),
    		array("name" =>"ministério", "count" => 0, "type" =>"Acervo"),
    		array("name" =>"mirante", "count" => 0, "type" =>"Acervo"),
    		array("name" =>"mobiliário", "count" => 0, "type" =>"Acervo"),
    		array("name" =>"montante", "count" => 0, "type" =>"Acervo"),
    		array("name" =>"monumento", "count" => 0, "type" =>"Acervo"),
    		array("name" =>"mosaico ", "count" => 0, "type" =>"Acervo"),
    		array("name" =>"mural", "count" => 0, "type" =>"Acervo"),
    		array("name" =>"mureta", "count" => 0, "type" =>"Acervo"),
    		array("name" =>"muro ", "count" => 0, "type" =>"Acervo"),
    		array("name" =>"muro de arrimo ", "count" => 0, "type" =>"Acervo"),
    		array("name" =>"museu ", "count" => 0, "type" =>"Acervo"),
    		array("name" =>"muxarabi", "count" => 0, "type" =>"Acervo"),
    		array("name" =>"óculo", "count" => 0, "type" =>"Acervo"),
    		array("name" =>"orfanato", "count" => 0, "type" =>"Acervo"),
    		array("name" =>"ornamento", "count" => 0, "type" =>"Acervo"),
    		array("name" =>"painel", "count" => 0, "type" =>"Acervo"),
    		array("name" =>"palacete", "count" => 0, "type" =>"Acervo"),
    		array("name" =>"palha", "count" => 0, "type" =>"Acervo"),
    		array("name" =>"papel de parede", "count" => 0, "type" =>"Acervo"),
    		array("name" =>"paralelepípedo", "count" => 0, "type" =>"Acervo"),
    		array("name" =>"parede", "count" => 0, "type" =>"Acervo"),
    		array("name" =>"parede curva", "count" => 0, "type" =>"Acervo"),
    		array("name" =>"parque", "count" => 0, "type" =>"Acervo"),
    		array("name" =>"passarela", "count" => 0, "type" =>"Acervo"),
    		array("name" =>"pastilha", "count" => 0, "type" =>"Acervo"),
    		array("name" =>"patamar", "count" => 0, "type" =>"Acervo"),
    		array("name" =>"pátio", "count" => 0, "type" =>"Acervo"),
    		array("name" =>"pátio de manobra", "count" => 0, "type" =>"Acervo"),
    		array("name" =>"pau a pique", "count" => 0, "type" =>"Acervo"),
    		array("name" =>"pavilhão", "count" => 0, "type" =>"Acervo"),
    		array("name" =>"pedra", "count" => 0, "type" =>"Acervo"),
    		array("name" =>"peitoril", "count" => 0, "type" =>"Acervo"),
    		array("name" =>"pergolado", "count" => 0, "type" =>"Acervo"),
    		array("name" =>"pilar", "count" => 0, "type" =>"Acervo"),
    		array("name" =>"pilarete", "count" => 0, "type" =>"Acervo"),
    		array("name" =>"pilastra", "count" => 0, "type" =>"Acervo"),
    		array("name" =>"piloti", "count" => 0, "type" =>"Acervo"),
    		array("name" =>"pingadeira", "count" => 0, "type" =>"Acervo"),
    		array("name" =>"piscina", "count" => 0, "type" =>"Acervo"),
    		array("name" =>"piso", "count" => 0, "type" =>"Acervo"),
    		array("name" =>"placa ", "count" => 0, "type" =>"Acervo"),
    		array("name" =>"placa pré moldada", "count" => 0, "type" =>"Acervo"),
    		array("name" =>"planetário", "count" => 0, "type" =>"Acervo"),
    		array("name" =>"planície", "count" => 0, "type" =>"Acervo"),
    		array("name" =>"plano inclinado", "count" => 0, "type" =>"Acervo"),
    		array("name" =>"plástico", "count" => 0, "type" =>"Acervo"),
    		array("name" =>"plataforma", "count" => 0, "type" =>"Acervo"),
    		array("name" =>"platibanda", "count" => 0, "type" =>"Acervo"),
    		array("name" =>"ponte", "count" => 0, "type" =>"Acervo"),
    		array("name" =>"porta", "count" => 0, "type" =>"Acervo"),
    		array("name" =>"porta de correr", "count" => 0, "type" =>"Acervo"),
    		array("name" =>"porta de duas folhas", "count" => 0, "type" =>"Acervo"),
    		array("name" =>"portão", "count" => 0, "type" =>"Acervo"),
    		array("name" =>"portão de correr", "count" => 0, "type" =>"Acervo"),
    		array("name" =>"pórtico", "count" => 0, "type" =>"Acervo"),
    		array("name" =>"portinhola", "count" => 0, "type" =>"Acervo"),
    		array("name" =>"poste", "count" => 0, "type" =>"Acervo"),
    		array("name" =>"posto de gasolina", "count" => 0, "type" =>"Acervo"),
    		array("name" =>"pousada", "count" => 0, "type" =>"Acervo"),
    		array("name" =>"praça", "count" => 0, "type" =>"Acervo"),
    		array("name" =>"praia", "count" => 0, "type" =>"Acervo"),
    		array("name" =>"prefeitura", "count" => 0, "type" =>"Acervo"),
    		array("name" =>"pvc", "count" => 0, "type" =>"Acervo"),
    		array("name" =>"quadra", "count" => 0, "type" =>"Acervo"),
    		array("name" =>"quadra poliesportiva", "count" => 0, "type" =>"Acervo"),
    		array("name" =>"rampa", "count" => 0, "type" =>"Acervo"),
    		array("name" =>"represa", "count" => 0, "type" =>"Acervo"),
    		array("name" =>"reservatório", "count" => 0, "type" =>"Acervo"),
    		array("name" =>"residência", "count" => 0, "type" =>"Acervo"),
    		array("name" =>"resort", "count" => 0, "type" =>"Acervo"),
    		array("name" =>"restaurante", "count" => 0, "type" =>"Acervo"),
    		array("name" =>"rio", "count" => 0, "type" =>"Acervo"),
    		array("name" =>"ripa ", "count" => 0, "type" =>"Acervo"),
    		array("name" =>"rodovia", "count" => 0, "type" =>"Acervo"),
    		array("name" =>"rosácea", "count" => 0, "type" =>"Acervo"),
    		array("name" =>"rua", "count" => 0, "type" =>"Acervo"),
    		array("name" =>"rufo", "count" => 0, "type" =>"Acervo"),
    		array("name" =>"sacada", "count" => 0, "type" =>"Acervo"),
    		array("name" =>"saguão", "count" => 0, "type" =>"Acervo"),
    		array("name" =>"saibro", "count" => 0, "type" =>"Acervo"),
    		array("name" =>"sala", "count" => 0, "type" =>"Acervo"),
    		array("name" =>"sala de estar", "count" => 0, "type" =>"Acervo"),
    		array("name" =>"sala de reunião", "count" => 0, "type" =>"Acervo"),
    		array("name" =>"salão  ", "count" => 0, "type" =>"Acervo"),
    		array("name" =>"sapata corrida", "count" => 0, "type" =>"Acervo"),
    		array("name" =>"secretaria", "count" => 0, "type" =>"Acervo"),
    		array("name" =>"senzala", "count" => 0, "type" =>"Acervo"),
    		array("name" =>"shaft", "count" => 0, "type" =>"Acervo"),
    		array("name" =>"shed", "count" => 0, "type" =>"Acervo"),
    		array("name" =>"silo", "count" => 0, "type" =>"Acervo"),
    		array("name" =>"sinagoga", "count" => 0, "type" =>"Acervo"),
    		array("name" =>"sindicato", "count" => 0, "type" =>"Acervo"),
    		array("name" =>"superquadra", "count" => 0, "type" =>"Acervo"),
    		array("name" =>"tabique", "count" => 0, "type" =>"Acervo"),
    		array("name" =>"tábua", "count" => 0, "type" =>"Acervo"),
    		array("name" =>"taipa de mão", "count" => 0, "type" =>"Acervo"),
    		array("name" =>"taipa de pilão", "count" => 0, "type" =>"Acervo"),
    		array("name" =>"taipa de sopapo", "count" => 0, "type" =>"Acervo"),
    		array("name" =>"tapume", "count" => 0, "type" =>"Acervo"),
    		array("name" =>"teatro", "count" => 0, "type" =>"Acervo"),
    		array("name" =>"tecido", "count" => 0, "type" =>"Acervo"),
    		array("name" =>"telha", "count" => 0, "type" =>"Acervo"),
    		array("name" =>"telha", "count" => 0, "type" =>"Acervo"),
    		array("name" =>"telhado", "count" => 0, "type" =>"Acervo"),
    		array("name" =>"telhado duas águas", "count" => 0, "type" =>"Acervo"),
    		array("name" =>"telhado invertido", "count" => 0, "type" =>"Acervo"),
    		array("name" =>"telhado quatro águas", "count" => 0, "type" =>"Acervo"),
    		array("name" =>"telhado uma água", "count" => 0, "type" =>"Acervo"),
    		array("name" =>"templo", "count" => 0, "type" =>"Acervo"),
    		array("name" =>"tenda", "count" => 0, "type" =>"Acervo"),
    		array("name" =>"terça", "count" => 0, "type" =>"Acervo"),
    		array("name" =>"terraço", "count" => 0, "type" =>"Acervo"),
    		array("name" =>"terraço jardim", "count" => 0, "type" =>"Acervo"),
    		array("name" =>"terreiro", "count" => 0, "type" =>"Acervo"),
    		array("name" =>"tesoura", "count" => 0, "type" =>"Acervo"),
    		array("name" =>"tesoura metálica", "count" => 0, "type" =>"Acervo"),
    		array("name" =>"tijolo de barro", "count" => 0, "type" =>"Acervo"),
    		array("name" =>"tinta", "count" => 0, "type" =>"Acervo"),
    		array("name" =>"tirante", "count" => 0, "type" =>"Acervo"),
    		array("name" =>"toldo", "count" => 0, "type" =>"Acervo"),
    		array("name" =>"torre", "count" => 0, "type" =>"Acervo"),
    		array("name" =>"treliça", "count" => 0, "type" =>"Acervo"),
    		array("name" =>"tribunal", "count" => 0, "type" =>"Acervo"),
    		array("name" =>"trilho", "count" => 0, "type" =>"Acervo"),
    		array("name" =>"túmulo", "count" => 0, "type" =>"Acervo"),
    		array("name" =>"umbral", "count" => 0, "type" =>"Acervo"),
    		array("name" =>"usina", "count" => 0, "type" =>"Acervo"),
    		array("name" =>"usina hidrelétrica", "count" => 0, "type" =>"Acervo"),
    		array("name" =>"vale", "count" => 0, "type" =>"Acervo"),
    		array("name" =>"vão", "count" => 0, "type" =>"Acervo"),
    		array("name" =>"varanda", "count" => 0, "type" =>"Acervo"),
    		array("name" =>"veneziana", "count" => 0, "type" =>"Acervo"),
    		array("name" =>"verga", "count" => 0, "type" =>"Acervo"),
    		array("name" =>"vergalhão", "count" => 0, "type" =>"Acervo"),
    		array("name" =>"verniz", "count" => 0, "type" =>"Acervo"),
    		array("name" =>"viaduto", "count" => 0, "type" =>"Acervo"),
    		array("name" =>"vidro", "count" => 0, "type" =>"Acervo"),
    		array("name" =>"viela", "count" => 0, "type" =>"Acervo"),
    		array("name" =>"viga", "count" => 0, "type" =>"Acervo"),
    		array("name" =>"vinil", "count" => 0, "type" =>"Acervo"),
    		array("name" =>"vitral", "count" => 0, "type" =>"Acervo"),
    		array("name" =>"vitrine", "count" => 0, "type" =>"Acervo"),
    		array("name" =>"voluta", "count" => 0, "type" =>"Acervo"),
		));
	}

	/**
	 * Reverse the migrations.
	 *
	 * @return void
	 */
	public function down()
	{
		//
	}

}
